/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import cjb.ci.CtrlInterfaz;
import dao.ClienteDao;
import dao.DetalleVentaDao;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Detalle_Venta;

/**
 *
 * @author chemo
 */
public class ReportesVentas extends javax.swing.JFrame
{

    /**
     * Creates new form Cliente
     */
    public ReportesVentas()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetalleVenta = new javax.swing.JTable();
        masVendido = new javax.swing.JCheckBox();
        aceptar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        totalPrecio = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        total = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaDetalleVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID", "ID VENTAS", "ID PRODUCTO", "CANTIDAD", "PRECIO"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaDetalleVenta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 550, 440));

        masVendido.setText("MAS VENDIDO");
        jPanel1.add(masVendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        aceptar.setText("ACEPTAR");
        aceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        limpiar.setText("LIMPIAR");
        limpiar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                limpiarActionPerformed(evt);
            }
        });
        jPanel1.add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 80, -1));

        totalPrecio.setText("TOTAL PRECIO");
        jPanel1.add(totalPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel1.setText("TOTAL PRECIO:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        total.setColumns(20);
        total.setRows(5);
        jScrollPane2.setViewportView(total);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 60, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        llenarTablaDetalleVenta();
    }//GEN-LAST:event_formWindowOpened

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aceptarActionPerformed
    {//GEN-HEADEREND:event_aceptarActionPerformed
        if (masVendido.isSelected())
        {
            llenarTablaTop5ProductosMasVendidos(true);
        } else
        {
            if (totalPrecio.isSelected())
            {
                double totalPrecio = DetalleVentaDao.calcularSumaPrecio();
                total.setText(String.format("%.2f", totalPrecio));
            } else
            {
            }
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_limpiarActionPerformed
    {//GEN-HEADEREND:event_limpiarActionPerformed
        llenarTablaDetalleVenta();
        masVendido.setSelected(false);
        totalPrecio.setSelected(false);
        CtrlInterfaz.limpia(total);
    }//GEN-LAST:event_limpiarActionPerformed

    private void llenarTablaTop5ProductosMasVendidos(boolean aplicarTop5)
    {
        DefaultTableModel modelo = (DefaultTableModel) tablaDetalleVenta.getModel();
        modelo.setRowCount(0); 

        List<Detalle_Venta> detallesVenta;

        if (aplicarTop5)
        {
            detallesVenta = DetalleVentaDao.listarTop5ProductosMasVendidos();
        } else
        {
            detallesVenta = DetalleVentaDao.listarDetalleVentas();
        }

        for (Detalle_Venta detalle : detallesVenta)
        {
            modelo.addRow(new Object[]
            {
                detalle.getIdDetalleVenta(), 
                detalle.getIdVentas(), 
                detalle.getIdProducto(), 
                detalle.getCantidad(), 
                detalle.getPrecio()               
            });
        }
    }

    private void llenarTablaDetalleVenta()
    {
        DefaultTableModel modelo = (DefaultTableModel) tablaDetalleVenta.getModel();
        modelo.setRowCount(0);

        List<Detalle_Venta> detallesVenta = DetalleVentaDao.listarDetalleVentas();

        for (Detalle_Venta detalle : detallesVenta)
        {
            modelo.addRow(new Object[]
            {
                detalle.getIdDetalleVenta(),
                detalle.getIdVentas(),
                detalle.getIdProducto(),
                detalle.getCantidad(),
                detalle.getPrecio()
            });
        }

        if (detallesVenta.isEmpty())
        {
            System.out.println("No se encontraron detalles de venta.");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ReportesVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ReportesVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ReportesVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ReportesVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ReportesVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limpiar;
    private javax.swing.JCheckBox masVendido;
    private javax.swing.JTable tablaDetalleVenta;
    private javax.swing.JTextArea total;
    private javax.swing.JCheckBox totalPrecio;
    // End of variables declaration//GEN-END:variables
}
