/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import cjb.ci.CtrlInterfaz;
import dao.VendedorDao;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chemo
 */
public class VtnVendedor extends javax.swing.JFrame
{

    /**
     * Creates new form Cliente
     */
    public VtnVendedor()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        dni = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        estado = new javax.swing.JComboBox<>();
        agregar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        nuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DNI:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 37, -1));

        jLabel2.setText("NOMBRE:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 60, -1));

        jLabel3.setText("TELEFONO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel4.setText("ESTADO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 550, 30));
        jPanel1.add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 210, -1));
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 210, -1));

        telefono.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                telefonoActionPerformed(evt);
            }
        });
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 210, -1));

        estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        estado.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                estadoActionPerformed(evt);
            }
        });
        jPanel1.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 210, -1));

        agregar.setText("AGREGAR");
        agregar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                agregarActionPerformed(evt);
            }
        });
        jPanel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 120, -1));

        actualizar.setText("ACTUALIZAR");
        actualizar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                actualizarActionPerformed(evt);
            }
        });
        jPanel1.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 120, -1));

        eliminar.setText("ELIMINAR");
        eliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 120, -1));

        nuevo.setText("NUEVO");
        nuevo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nuevoActionPerformed(evt);
            }
        });
        jPanel1.add(nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 120, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID", "DNI", "NOMBRE", "TELEFONO", "ESTADO"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 550, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_telefonoActionPerformed
    {//GEN-HEADEREND:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        llenarTablaVendedor();
    }//GEN-LAST:event_formWindowOpened

    private void agregarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_agregarActionPerformed
    {//GEN-HEADEREND:event_agregarActionPerformed
        String dni = this.dni.getText();
        String nombre = this.nombre.getText();
        String telefono = this.telefono.getText();
        boolean estado = obtenerEstadoSeleccionado();

        //modelo.Cliente nuevoCliente = new modelo.Cliente(0, dni, nombre, direccion, estado);
        modelo.Vendedor nuevoVendedor = new modelo.Vendedor(0, dni, nombre, telefono, estado);
        VendedorDao.agregarVendedor(nuevoVendedor);

        llenarTablaVendedor();
    }//GEN-LAST:event_agregarActionPerformed

    private void estadoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_estadoActionPerformed
    {//GEN-HEADEREND:event_estadoActionPerformed

    }//GEN-LAST:event_estadoActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_actualizarActionPerformed
    {//GEN-HEADEREND:event_actualizarActionPerformed
        int filaSeleccionada = tabla.getSelectedRow();
        if (filaSeleccionada != -1)
        {
            try
            {
                int idVendedor = Integer.parseInt(tabla.getValueAt(filaSeleccionada, 0).toString());
                String dni = this.dni.getText().trim();
                String nombre = this.nombre.getText().trim();
                String telefono = this.telefono.getText().trim();

                if (dni.isEmpty() || nombre.isEmpty() || telefono.isEmpty())
                {
                    javax.swing.JOptionPane.showMessageDialog(this, "DNI, nombre y teléfono no pueden estar vacíos.");
                    return;
                }

                boolean estado = obtenerEstadoSeleccionado();

                modelo.Vendedor vendedorActualizado = new modelo.Vendedor(idVendedor, dni, nombre, telefono, estado);

                VendedorDao.actualizarVendedor(vendedorActualizado);

                llenarTablaVendedor();
            } catch (NumberFormatException e)
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al obtener el ID del vendedor. Por favor, selecciona un vendedor válido.");
            }
        } else
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona un vendedor para actualizar.");
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nuevoActionPerformed
    {//GEN-HEADEREND:event_nuevoActionPerformed
        CtrlInterfaz.limpia(dni, nombre, telefono);
        estado.setSelectedIndex(0);
    }//GEN-LAST:event_nuevoActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_eliminarActionPerformed
    {//GEN-HEADEREND:event_eliminarActionPerformed
        int filaSeleccionada = tabla.getSelectedRow();
        if (filaSeleccionada != -1)
        {
            int idVendedor = Integer.parseInt(tabla.getValueAt(filaSeleccionada, 0).toString());

            int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
                    "¿Estás seguro de que deseas eliminar este vendedor?",
                    "Confirmar eliminación",
                    javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirmacion == javax.swing.JOptionPane.YES_OPTION)
            {
                VendedorDao.eliminarVendedor(idVendedor);
                llenarTablaVendedor();
            }
        } else
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona un vendedor para eliminar.");
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private boolean obtenerEstadoSeleccionado()
    {
        String estadoSeleccionado = (String) estado.getSelectedItem();
        return "Activo".equals(estadoSeleccionado);
    }

    private void llenarTablaVendedor()
    {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        modelo.setRowCount(0); 

        List<modelo.Vendedor> vendedores = VendedorDao.listarVendedores();

        for (modelo.Vendedor vendedor : vendedores)
        {
            modelo.addRow(new Object[]
            {
                vendedor.getIdVendedor(),
                vendedor.getDni(),
                vendedor.getNombre(),
                vendedor.getTelefono(),
                vendedor.isEstado() ? "Activo" : "Inactivo"
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton agregar;
    private javax.swing.JTextField dni;
    private javax.swing.JButton eliminar;
    private javax.swing.JComboBox<String> estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton nuevo;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
